export const gpuiComponents = [
  {
    slug: "accordion",
    title: "Accordion",
    href: "/gpui/accordion",
    description: "垂直堆叠的交互标题，逐段展开内容。",
    category: "Disclosure",
    platform: "Desktop",
  },
  {
    slug: "alert",
    title: "Alert",
    href: "/gpui/alert",
    description: "用于吸引用户注意的醒目提示块，支持图标、描述与操作按钮。",
    category: "Feedback",
    platform: "Desktop",
  },
  {
    slug: "alert-dialog",
    title: "Alert Dialog",
    href: "/gpui/alert-dialog",
    description: "打断用户并等待确认或取消的模态对话框。",
    category: "Overlay",
    platform: "Desktop",
  },
  {
    slug: "aspect-ratio",
    title: "Aspect Ratio",
    href: "/gpui/aspect-ratio",
    description: "按固定宽高比约束内容的容器。",
    category: "Layout",
    platform: "Desktop",
  },
  {
    slug: "attachment",
    title: "Attachment",
    href: "/gpui/attachment",
    description: "展示文件或图片附件：媒体区、元数据、上传状态与操作。",
    category: "Data Display",
    platform: "Desktop",
  },
  {
    slug: "avatar",
    title: "Avatar",
    href: "/gpui/avatar",
    description: "带图片与首字母 fallback 的圆形用户头像，支持角标与叠压组。",
    category: "Data Display",
    platform: "Desktop",
  },
  {
    slug: "badge",
    title: "Badge",
    href: "/gpui/badge",
    description: "紧凑的状态徽章：六种变体、内联图标、spinner 与可点击链接。",
    category: "Data Display",
    platform: "Desktop",
  },
  {
    slug: "breadcrumb",
    title: "Breadcrumb",
    href: "/gpui/breadcrumb",
    description: "用层级链接展示当前资源的路径，支持折叠与 RTL。",
    category: "Navigation",
    platform: "Desktop",
  },
  {
    slug: "bubble",
    title: "Bubble",
    href: "/gpui/bubble",
    description: "聊天气泡：七种变体、收发对齐、分组、reaction 与可折叠长文本。",
    category: "Data Display",
    platform: "Desktop",
  },
  {
    slug: "button",
    title: "Button",
    href: "/gpui/button",
    description: "六种变体、八种尺寸、图标、spinner 与按钮组的按钮元素。",
    category: "Actions",
    platform: "Desktop",
  },
] as const;
