export const gpuiComponents = [
  {
    slug: "accordion",
    title: "Accordion",
    href: "/gpui/accordion",
    description: "垂直堆叠的交互标题，逐段展开内容。",
    category: "Disclosure",
    platform: "Desktop",
  },
  {
    slug: "alert",
    title: "Alert",
    href: "/gpui/alert",
    description: "用于吸引用户注意的醒目提示块，支持图标、描述与操作按钮。",
    category: "Feedback",
    platform: "Desktop",
  },
  {
    slug: "alert-dialog",
    title: "Alert Dialog",
    href: "/gpui/alert-dialog",
    description: "打断用户并等待确认或取消的模态对话框。",
    category: "Overlay",
    platform: "Desktop",
  },
  {
    slug: "aspect-ratio",
    title: "Aspect Ratio",
    href: "/gpui/aspect-ratio",
    description: "按固定宽高比约束内容的容器。",
    category: "Layout",
    platform: "Desktop",
  },
  {
    slug: "attachment",
    title: "Attachment",
    href: "/gpui/attachment",
    description: "展示文件或图片附件：媒体区、元数据、上传状态与操作。",
    category: "Data Display",
    platform: "Desktop",
  },
  {
    slug: "avatar",
    title: "Avatar",
    href: "/gpui/avatar",
    description: "带图片与首字母 fallback 的圆形用户头像，支持角标与叠压组。",
    category: "Data Display",
    platform: "Desktop",
  },
  {
    slug: "badge",
    title: "Badge",
    href: "/gpui/badge",
    description: "紧凑的状态徽章：六种变体、内联图标、spinner 与可点击链接。",
    category: "Data Display",
    platform: "Desktop",
  },
  {
    slug: "breadcrumb",
    title: "Breadcrumb",
    href: "/gpui/breadcrumb",
    description: "用层级链接展示当前资源的路径，支持折叠与 RTL。",
    category: "Navigation",
    platform: "Desktop",
  },
  {
    slug: "bubble",
    title: "Bubble",
    href: "/gpui/bubble",
    description: "聊天气泡：七种变体、收发对齐、分组、reaction 与可折叠长文本。",
    category: "Data Display",
    platform: "Desktop",
  },
  {
    slug: "button",
    title: "Button",
    href: "/gpui/button",
    description: "六种变体、八种尺寸、图标、spinner 与按钮组的按钮元素。",
    category: "Actions",
    platform: "Desktop",
  },
  {
    slug: "button-group",
    title: "Button Group",
    href: "/gpui/button-group",
    description: "把相关按钮合并成组：横纵排布、分隔线、文本格与 split 按钮。",
    category: "Actions",
    platform: "Desktop",
  },
  {
    slug: "calendar",
    title: "Calendar",
    href: "/gpui/calendar",
    description: "单日期或范围选择日历：双月视图、月/年下拉、预设、日期时间组合与禁用日期。",
    category: "Date & Time",
    platform: "Desktop",
  },
  {
    slug: "card",
    title: "Card",
    href: "/gpui/card",
    description: "卡片容器：header/content/footer 分区、间距缩放、贴边媒体与分隔线。",
    category: "Layout",
    platform: "Desktop",
  },
  {
    slug: "carousel",
    title: "Carousel",
    href: "/gpui/carousel",
    description: "Embla 风格的滑动轮播：动画轨道、首尾导航、loop 回绕、垂直模式与键盘控制。",
    category: "Data Display",
    platform: "Desktop",
  },
  {
    slug: "chart",
    title: "Chart",
    href: "/gpui/chart",
    description: "自绘图表：分组/堆叠柱状、折线、面积、环形，悬停 tooltip、legend 与明暗主题。",
    category: "Data Display",
    platform: "Desktop",
  },
  {
    slug: "checkbox",
    title: "Checkbox",
    href: "/gpui/checkbox",
    description: "三态复选框：label/description 组合、invalid 校验态、禁用与表头全选。",
    category: "Forms",
    platform: "Desktop",
  },
  {
    slug: "collapsible",
    title: "Collapsible",
    href: "/gpui/collapsible",
    description: "可展开/收起的面板：chevron 触发器、高度揭幕动画、嵌套文件树。",
    category: "Disclosure",
    platform: "Desktop",
  },
  {
    slug: "combobox",
    title: "Combobox",
    href: "/gpui/combobox",
    description: "可搜索的选择器：输入过滤、单选/多选 chips、键盘导航与空态。",
    category: "Forms",
    platform: "Desktop",
  },
  {
    slug: "command",
    title: "Command",
    href: "/gpui/command",
    description: "cmdk 风格命令面板：搜索过滤、分组、快捷键标签与键盘导航。",
    category: "Navigation",
    platform: "Desktop",
  },
  {
    slug: "context-menu",
    title: "Context Menu",
    href: "/gpui/context-menu",
    description: "右键触发的浮层菜单：子菜单、复选/单选项、快捷键与破坏性操作。",
    category: "Navigation",
    platform: "Desktop",
  },
] as const;
