import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
const names = ["PhotoStack", "HoldToConfirm", "MiniPlayer", "ReactionPicker", "SendButton", "PullToSearch"];
const sources = Object.fromEntries(await Promise.all(names.map(async name => [name, await readFile(resolve(root, `examples/swiftui/${name}.swift`), "utf8")])));
const output = `// Generated by scripts/sync-swift.mjs. Edit examples/swiftui/*.swift instead.\nexport const swiftSources = ${JSON.stringify(sources, null, 2)} as const;\n`;
await mkdir(resolve(root, "lib/generated"), { recursive: true });
if (process.argv.includes("--check")) {
  if (await readFile(resolve(root, "lib/generated/swift-sources.ts"), "utf8").catch(() => "") !== output) {
    throw new Error("Swift source data is stale. Run npm run sync:swift.");
  }
  console.log("Swift source downloads match the canonical files.");
} else {
  await writeFile(resolve(root, "lib/generated/swift-sources.ts"), output);
  console.log(`Synced ${names.length} SwiftUI components.`);
}
